# .github/workflows/deploy-gcp.yml
name: Deploy to GCP VM

on:
  push:
    branches:
      - Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to VM
        uses: google-github-actions/ssh-compute@v2
        with:
          instance_name: '${{ secrets.VM_INSTANCE_NAME }}'
          zone: '${{ secrets.VM_ZONE }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: |
            set -e
            # Quick check for SSH key setup (optional, for debugging)
            if [ ! -f ~/.ssh/id_rsa ]; then
              echo "Warning: SSH key not found locally on VM. Ensure it's installed."
            fi
            
            cd ~
            if [ -d "video-player-website" ]; then
              cd video-player-website
              git pull
            else
              git clone https://github.com/${{ github.repository }}.git .
              # Note: Cloned directly into the dir to avoid extra 'video-player-website' subdir
            fi
            
            echo "Building and deploying services..."
            sudo docker-compose up --build -d
            
            echo "Pruning old Docker images to save space..."
            sudo docker image prune -af
