# .github/workflows/deploy-gcp.yml
name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  # For auth

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Deploy to VM
        uses: google-github-actions/ssh-compute@v2
        with:
          instance_name: '${{ secrets.VM_INSTANCE_NAME }}'
          zone: '${{ secrets.VM_ZONE }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: |
            set -e

            # Add Docker's official GPG key:
            sudo apt-get update
            sudo apt-get install ca-certificates curl
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc

            # Add the repository to Apt sources:
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update

            # Install Docker and essential tools
            echo "Installing Docker and dependencies..."
            sudo apt-get install -y git docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin python3 python3-pip nodejs npm

            # Ensure Docker service is running
            sudo systemctl enable docker
            sudo systemctl start docker

            # Clone or update repository
            cd ~
            if [ -d "Video-Player-Website" ]; then
              cd Video-Player-Website
              sudo git config --global --add safe.directory /home/runner/Video-Player-Website
              sudo git pull
            else
              sudo git clone https://github.com/${{ github.repository }}.git
              cd Video-Player-Website
            fi

            echo "Building and deploying services..."
            sudo docker compose up --build -d

            echo "Pruning old Docker images to save space..."
            sudo docker image prune -af