# .github/workflows/deploy-gcp.yml
name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to VM
        uses: google-github-actions/gcloud-compute-ssh@v2
        with:
          instance_name: '${{ secrets.VM_INSTANCE_NAME }}'
          zone: '${{ secrets.VM_ZONE }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'
          command: |
            set -e
            cd ~
            if [ -d "video-player-website" ]; then
              cd video-player-website
              git pull
            else
              git clone https://github.com/${{ github.repository }}.git
              cd video-player-website
            fi
            
            echo "Building and deploying services..."
            sudo docker-compose up --build -d
            
            echo "Pruning old Docker images to save space..."
            sudo docker image prune -af